"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 3.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from dotenv import load_dotenv
from arh import getEncConf
load_dotenv()

"""
Costume Config ARH
"""
if os.getenv('IS_PRODUCTION',None):
    PRODUCTION =True
    DEBUG = False
elif os.getenv('IS_DEVELOPMENT',None):
    PRODUCTION = False
    DEBUG = True

handler404 = 'app.views.error404'
HOST_DEPLOY = ""
CREATOR = os.getenv("CREATOR")
PRODUCT_ID = os.getenv("PRODUCT_ID")
PRODUCT = os.getenv("PRODUCT")
SECRET = getEncConf("SECRET")
ROOT_API = "api"
VERSION = "v1.0"

EMAIL_HOST =  'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = getEncConf("SMTP_USERNAME")
EMAIL_HOST_PASSWORD =getEncConf("SMTP_PASSWORD")
EMAIL_USE_TLS = True


TWILIO_ID = ""
TWILIO_TOKEN=""
TWILIO_PROVIDER_NUMBER = 14155238886

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = getEncConf("SECRET")
# SECURITY WARNING: don't run with debug turned on in production!


ALLOWED_HOSTS = [HOST_DEPLOY,"localhost"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware'
]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,"templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'




DATABASES={
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME':'d64nnaq88o5a2v',
        'USER':'ibsteoqbuxunpj',
        'PASSWORD':'4cb8949eebb18cb2ce5405230144015ae09b7ae35a6251ec87ea911778ca6f57',
        'HOST':'ec2-35-172-73-125.compute-1.amazonaws.com',
        'PORT':5432
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Jakarta'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR,'staticfiles')
STATIC_URL = '/static/'
